# vee5ss-vendor-blobs.mk — generado por setup-makefiles.sh
# NO editar manualmente.

LOCAL_PATH := vendor/lge/vee5ss/proprietary

PRODUCT_COPY_FILES += \
    $(LOCAL_PATH)/app/MtkBt.apk:system/app/MtkBt.apk \
    $(LOCAL_PATH)/bin/6620_launcher:system/bin/6620_launcher \
    $(LOCAL_PATH)/bin/btconfig:system/bin/btconfig \
    $(LOCAL_PATH)/bin/btlogmask:system/bin/btlogmask \
    $(LOCAL_PATH)/bin/hald:system/bin/hald \
    $(LOCAL_PATH)/bin/mtkbt:system/bin/mtkbt \
    $(LOCAL_PATH)/bin/stp_dump3:system/bin/stp_dump3 \
    $(LOCAL_PATH)/bin/wpa_supplicant:system/bin/wpa_supplicant \
    $(LOCAL_PATH)/etc/wifi/p2p_supplicant.conf:system/etc/wifi/p2p_supplicant.conf \
    $(LOCAL_PATH)/etc/wifi/wpa_supplicant.conf:system/etc/wifi/wpa_supplicant.conf \
    $(LOCAL_PATH)/lib/egl/egl.cfg:system/lib/egl/egl.cfg \
    $(LOCAL_PATH)/lib/egl/libGLES_android.so:system/lib/egl/libGLES_android.so \
    $(LOCAL_PATH)/lib/mtk-ril.so:system/lib/mtk-ril.so \
    $(LOCAL_PATH)/lib/librilmtk.so:system/lib/librilmtk.so \
    $(LOCAL_PATH)/lib/libutilrilmtk.so:system/lib/libutilrilmtk.so \
    $(LOCAL_PATH)/lib/liblgpclient_jni.so:system/lib/liblgpclient_jni.so \
    $(LOCAL_PATH)/lib/hw/audio_policy.default.so:system/lib/hw/audio_policy.default.so \
    $(LOCAL_PATH)/lib/hw/audio.primary.default.so:system/lib/hw/audio.primary.default.so \
    $(LOCAL_PATH)/lib/libaudio.primary.default.so:system/lib/libaudio.primary.default.so \
    $(LOCAL_PATH)/lib/libaudio.primary.default.so:system/lib/hw/audio.primary.mt6575.so \
    $(LOCAL_PATH)/lib/libblisrc.so:system/lib/libblisrc.so \
    $(LOCAL_PATH)/lib/libbluetooth_relayer.so:system/lib/libbluetooth_relayer.so \
    $(LOCAL_PATH)/lib/libbtsniff.so:system/lib/libbtsniff.so \
    $(LOCAL_PATH)/lib/libem_bt_jni.so:system/lib/libem_bt_jni.so \
    $(LOCAL_PATH)/lib/libengbttest_jni.so:system/lib/libengbttest_jni.so \
    $(LOCAL_PATH)/lib/libextavrcp.so:system/lib/libextavrcp.so \
    $(LOCAL_PATH)/lib/libextavrcp_jni.so:system/lib/libextavrcp_jni.so \
    $(LOCAL_PATH)/lib/libextbip.so:system/lib/libextbip.so \
    $(LOCAL_PATH)/lib/libextbip_jni.so:system/lib/libextbip_jni.so \
    $(LOCAL_PATH)/lib/libextbpp.so:system/lib/libextbpp.so \
    $(LOCAL_PATH)/lib/libextbpp_jni.so:system/lib/libextbpp_jni.so \
    $(LOCAL_PATH)/lib/libextdun_jni.so:system/lib/libextdun_jni.so \
    $(LOCAL_PATH)/lib/libextsys.so:system/lib/libextsys.so \
    $(LOCAL_PATH)/lib/libextsys_jni.so:system/lib/libextsys_jni.so \
    $(LOCAL_PATH)/lib/libextftp.so:system/lib/libextftp.so \
    $(LOCAL_PATH)/lib/libextftp_jni.so:system/lib/libextftp_jni.so \
    $(LOCAL_PATH)/lib/libexthid.so:system/lib/libexthid.so \
    $(LOCAL_PATH)/lib/libexthid_jni.so:system/lib/libexthid_jni.so \
    $(LOCAL_PATH)/lib/libextmap.so:system/lib/libextmap.so \
    $(LOCAL_PATH)/lib/libextmap_jni.so:system/lib/libextmap_jni.so \
    $(LOCAL_PATH)/lib/libextopp.so:system/lib/libextopp.so \
    $(LOCAL_PATH)/lib/libextopp_jni.so:system/lib/libextopp_jni.so \
    $(LOCAL_PATH)/lib/libextpan_jni.so:system/lib/libextpan_jni.so \
    $(LOCAL_PATH)/lib/libextpbap.so:system/lib/libextpbap.so \
    $(LOCAL_PATH)/lib/libextpbap_jni.so:system/lib/libextpbap_jni.so \
    $(LOCAL_PATH)/lib/libextsimap.so:system/lib/libextsimap.so \
    $(LOCAL_PATH)/lib/libextsimap_jni.so:system/lib/libextsimap_jni.so \
    $(LOCAL_PATH)/lib/libexttestmode.so:system/lib/libexttestmode.so \
    $(LOCAL_PATH)/lib/libhardware_legacy.so:system/lib/libhardware_legacy.so \
    $(LOCAL_PATH)/lib/libmtkbtextadp.so:system/lib/libmtkbtextadp.so \
    $(LOCAL_PATH)/lib/libmtkbtextpan.so:system/lib/libmtkbtextpan.so \
    $(LOCAL_PATH)/lib/libmtkbtextspp.so:system/lib/libmtkbtextspp.so \
    $(LOCAL_PATH)/lib/libpppbtdun.so:system/lib/libpppbtdun.so \
    $(LOCAL_PATH)/lib/libwpa_client.so:system/lib/libwpa_client.so \
    $(LOCAL_PATH)/lib/libtinyalsa.so:system/lib/libtinyalsa.so \
    $(LOCAL_PATH)/lib/libheadphonecompensationfilter.so:system/lib/libheadphonecompensationfilter.so \
    $(LOCAL_PATH)/lib/libspeech_enh_lib.so:system/lib/libspeech_enh_lib.so \
    $(LOCAL_PATH)/lib/libnexaudiorenderer.so:system/lib/libnexaudiorenderer.so \
    $(LOCAL_PATH)/lib/libaudioeffectsole.so:system/lib/libaudioeffectsole.so \
    $(LOCAL_PATH)/lib/hw/camera.default.so:system/lib/hw/camera.stock.mt6575.so \
    $(LOCAL_PATH)/lib/libcamera_client.so:system/lib/libcamera_client.so \
    $(LOCAL_PATH)/lib/libmhal.so:system/lib/libmhal.so \
    $(LOCAL_PATH)/lib/libmhalmdp.so:system/lib/libmhalmdp.so \
    $(LOCAL_PATH)/lib/libmhalscenario.so:system/lib/libmhalscenario.so \
    $(LOCAL_PATH)/lib/libmhaldrv.so:system/lib/libmhaldrv.so \
    $(LOCAL_PATH)/lib/libmhalcontent.so:system/lib/libmhalcontent.so \
    $(LOCAL_PATH)/lib/libmhalpipe.so:system/lib/libmhalpipe.so \
    $(LOCAL_PATH)/lib/libmexif.so:system/lib/libmexif.so \
    $(LOCAL_PATH)/lib/libeis.so:system/lib/libeis.so \
    $(LOCAL_PATH)/lib/libmpoencoder.so:system/lib/libmpoencoder.so \
    $(LOCAL_PATH)/lib/libmpo.so:system/lib/libmpo.so \
    $(LOCAL_PATH)/lib/libutilitysw.so:system/lib/libutilitysw.so \
    $(LOCAL_PATH)/lib/libmatv_cust.so:system/lib/libmatv_cust.so \
    $(LOCAL_PATH)/lib/hw/gps.default.so:system/lib/hw/gps.default.so \
    $(LOCAL_PATH)/lib/hw/gralloc.default.so:system/lib/hw/gralloc.default.so \
    $(LOCAL_PATH)/lib/hw/hwcomposer.mt6575.so:system/lib/hw/hwcomposer.mt6575.so \
    $(LOCAL_PATH)/lib/hw/lights.default.so:system/lib/hw/lights.default.so \
    $(LOCAL_PATH)/lib/libproxyhal.so:system/lib/libproxyhal.so \
    $(LOCAL_PATH)/lib/hw/mmumapper.mt6575.so:system/lib/hw/mmumapper.mt6575.so \
    $(LOCAL_PATH)/lib/hw/power.default.so:system/lib/hw/power.default.so \
    $(LOCAL_PATH)/lib/hw/sensors.mt6575.so:system/lib/hw/sensors.mt6575.so \
    $(LOCAL_PATH)/lib/modules/ccci.ko:system/lib/modules/ccci.ko \
    $(LOCAL_PATH)/lib/modules/ccci_plat.ko:system/lib/modules/ccci_plat.ko \
    $(LOCAL_PATH)/lib/modules/ccmni.ko:system/lib/modules/ccmni.ko \
    $(LOCAL_PATH)/lib/modules/devinfo.ko:system/lib/modules/devinfo.ko \
    $(LOCAL_PATH)/lib/modules/m4u.ko:system/lib/modules/m4u.ko \
    $(LOCAL_PATH)/lib/modules/mtk_drvb.ko:system/lib/modules/mtk_drvb.ko \
    $(LOCAL_PATH)/lib/modules/mtk_fm_drv.ko:system/lib/modules/mtk_fm_drv.ko \
    $(LOCAL_PATH)/lib/modules/mtk_fm_priv.ko:system/lib/modules/mtk_fm_priv.ko \
    $(LOCAL_PATH)/lib/modules/mtk_hif_sdio.ko:system/lib/modules/mtk_hif_sdio.ko \
    $(LOCAL_PATH)/lib/modules/mtk_hif_sdio_mt6628.ko:system/lib/modules/mtk_hif_sdio_mt6628.ko \
    $(LOCAL_PATH)/lib/modules/mtklfb.ko:system/lib/modules/mtklfb.ko \
    $(LOCAL_PATH)/lib/modules/mtk_stp_bt.ko:system/lib/modules/mtk_stp_bt.ko \
    $(LOCAL_PATH)/lib/modules/mtk_stp_bt_mt6628.ko:system/lib/modules/mtk_stp_bt_mt6628.ko \
    $(LOCAL_PATH)/lib/modules/mtk_stp_gps.ko:system/lib/modules/mtk_stp_gps.ko \
    $(LOCAL_PATH)/lib/modules/mtk_stp_gps_mt6628.ko:system/lib/modules/mtk_stp_gps_mt6628.ko \
    $(LOCAL_PATH)/lib/modules/mtk_stp_uart.ko:system/lib/modules/mtk_stp_uart.ko \
    $(LOCAL_PATH)/lib/modules/mtk_stp_uart_mt6628.ko:system/lib/modules/mtk_stp_uart_mt6628.ko \
    $(LOCAL_PATH)/lib/modules/mtk_stp_wmt.ko:system/lib/modules/mtk_stp_wmt.ko \
    $(LOCAL_PATH)/lib/modules/mtk_stp_wmt_mt6628.ko:system/lib/modules/mtk_stp_wmt_mt6628.ko \
    $(LOCAL_PATH)/lib/modules/mtk_wmt_wifi.ko:system/lib/modules/mtk_wmt_wifi.ko \
    $(LOCAL_PATH)/lib/modules/mtk_wmt_wifi_mt6628.ko:system/lib/modules/mtk_wmt_wifi_mt6628.ko \
    $(LOCAL_PATH)/lib/modules/pvrsrvkm.ko:system/lib/modules/pvrsrvkm.ko \
    $(LOCAL_PATH)/lib/modules/sec.ko:system/lib/modules/sec.ko \
    $(LOCAL_PATH)/lib/modules/vcodec_kernel_driver.ko:system/lib/modules/vcodec_kernel_driver.ko \
    $(LOCAL_PATH)/lib/modules/wlan.ko:system/lib/modules/wlan.ko \
    $(LOCAL_PATH)/lib/modules/wlan_mt6620.ko:system/lib/modules/wlan_mt6620.ko \
    $(LOCAL_PATH)/lib/modules/wlan_mt6628.ko:system/lib/modules/wlan_mt6628.ko \
    $(LOCAL_PATH)/etc/firmware/WIFI_RAM_CODE:system/etc/firmware/WIFI_RAM_CODE \
    $(LOCAL_PATH)/etc/firmware/WIFI_RAM_CODE_E6:system/etc/firmware/WIFI_RAM_CODE_E6 \
    $(LOCAL_PATH)/etc/firmware/WIFI_RAM_CODE_MT6628:system/etc/firmware/WIFI_RAM_CODE_MT6628 \
    $(LOCAL_PATH)/etc/firmware/WMT.cfg:system/etc/firmware/WMT.cfg \
    $(LOCAL_PATH)/etc/firmware/mt6620_patch_e3_0_hdr.bin:system/etc/firmware/mt6620_patch_e3_0_hdr.bin \
    $(LOCAL_PATH)/etc/firmware/mt6620_patch_e3_1_hdr.bin:system/etc/firmware/mt6620_patch_e3_1_hdr.bin \
    $(LOCAL_PATH)/etc/firmware/mt6620_patch_e3_2_hdr.bin:system/etc/firmware/mt6620_patch_e3_2_hdr.bin \
    $(LOCAL_PATH)/etc/firmware/mt6620_patch_e3_3_hdr.bin:system/etc/firmware/mt6620_patch_e3_3_hdr.bin \
    $(LOCAL_PATH)/etc/firmware/mt6620_patch_e6_hdr.bin:system/etc/firmware/mt6620_patch_e6_hdr.bin \
    $(LOCAL_PATH)/vendor/bin/pvrsrvctl:system/vendor/bin/pvrsrvctl \
    $(LOCAL_PATH)/vendor/lib/egl/libEGL_mtk.so:system/vendor/lib/egl/libEGL_mtk.so \
    $(LOCAL_PATH)/vendor/lib/egl/libGLESv1_CM_mtk.so:system/vendor/lib/egl/libGLESv1_CM_mtk.so \
    $(LOCAL_PATH)/vendor/lib/egl/libGLESv2_mtk.so:system/vendor/lib/egl/libGLESv2_mtk.so \
    $(LOCAL_PATH)/vendor/lib/hw/gralloc.mt6575.so:system/vendor/lib/hw/gralloc.mt6575.so \
    $(LOCAL_PATH)/vendor/lib/libglslcompiler.so:system/vendor/lib/libglslcompiler.so \
    $(LOCAL_PATH)/vendor/lib/libIMGegl.so:system/vendor/lib/libIMGegl.so \
    $(LOCAL_PATH)/vendor/lib/libpvr2d.so:system/vendor/lib/libpvr2d.so \
    $(LOCAL_PATH)/vendor/lib/libpvrANDROID_WSEGL.so:system/vendor/lib/libpvrANDROID_WSEGL.so \
    $(LOCAL_PATH)/vendor/lib/libPVRScopeServices.so:system/vendor/lib/libPVRScopeServices.so \
    $(LOCAL_PATH)/vendor/lib/libsrv_init.so:system/vendor/lib/libsrv_init.so \
    $(LOCAL_PATH)/vendor/lib/libsrv_um.so:system/vendor/lib/libsrv_um.so \
    $(LOCAL_PATH)/vendor/lib/libusc.so:system/vendor/lib/libusc.so \
    $(LOCAL_PATH)/bin/ccci_mdinit:system/bin/ccci_mdinit \
    $(LOCAL_PATH)/bin/ccci_fsd:system/bin/ccci_fsd \
    $(LOCAL_PATH)/bin/ccci_rpcd:system/bin/ccci_rpcd \
    $(LOCAL_PATH)/bin/gsm0710muxd:system/bin/gsm0710muxd \
    $(LOCAL_PATH)/etc/firmware/modem.img:system/etc/firmware/modem.img \
    $(LOCAL_PATH)/etc/firmware/DSP_ROM:system/etc/firmware/DSP_ROM \
    $(LOCAL_PATH)/lib/liblgpart.so:system/lib/liblgpart.so \
    $(LOCAL_PATH)/lib/libfile_op.so:system/lib/libfile_op.so \
    $(LOCAL_PATH)/lib/libhwm.so:system/lib/libhwm.so \
    $(LOCAL_PATH)/bin/nvram_daemon:system/bin/nvram_daemon
