# vee5ss-vendor-blobs.mk — generado por setup-makefiles.sh
# NO editar manualmente.

LOCAL_PATH := vendor/lge/vee5ss/proprietary

PRODUCT_COPY_FILES += \
    $(LOCAL_PATH)/etc/wifi/p2p_supplicant.conf:system/etc/wifi/p2p_supplicant.conf \
    $(LOCAL_PATH)/etc/wifi/wpa_supplicant.conf:system/etc/wifi/wpa_supplicant.conf \
    $(LOCAL_PATH)/lib/egl/egl.cfg:system/lib/egl/egl.cfg \
    $(LOCAL_PATH)/lib/egl/libGLES_android.so:system/lib/egl/libGLES_android.so \
    $(LOCAL_PATH)/lib/mtk-ril.so:system/lib/mtk-ril.so \
    $(LOCAL_PATH)/lib/librilmtk.so:system/lib/librilmtk.so \
    $(LOCAL_PATH)/lib/libutilrilmtk.so:system/lib/libutilrilmtk.so \
    $(LOCAL_PATH)/lib/liblgpclient_jni.so:system/lib/liblgpclient_jni.so \
    $(LOCAL_PATH)/lib/hw/audio_policy.default.so:system/lib/hw/audio_policy.default.so \
    $(LOCAL_PATH)/lib/hw/audio.primary.default.so:system/lib/hw/audio.primary.default.so \
    $(LOCAL_PATH)/lib/libaudiosetting.so:system/lib/libaudiosetting.so \
    $(LOCAL_PATH)/lib/libaudiocustparam.so:system/lib/libaudiocustparam.so \
    $(LOCAL_PATH)/lib/libaudiocompensationfilter.so:system/lib/libaudiocompensationfilter.so \
    $(LOCAL_PATH)/lib/libacdk.so:system/lib/libacdk.so \
    $(LOCAL_PATH)/lib/libaudioflinger.so:system/lib/libaudioflinger.so \
    $(LOCAL_PATH)/lib/libaudio.primary.default.so:system/lib/libaudio.primary.default.so \
    $(LOCAL_PATH)/lib/libaudio.primary.default.so:system/lib/hw/audio.primary.mt6575.so \
    $(LOCAL_PATH)/lib/libblisrc.so:system/lib/libblisrc.so \
    $(LOCAL_PATH)/lib/libmtk_drvb.so:system/lib/libmtk_drvb.so \
    $(LOCAL_PATH)/lib/libtinyalsa.so:system/lib/libtinyalsa.so \
    $(LOCAL_PATH)/lib/libheadphonecompensationfilter.so:system/lib/libheadphonecompensationfilter.so \
    $(LOCAL_PATH)/lib/libspeech_enh_lib.so:system/lib/libspeech_enh_lib.so \
    $(LOCAL_PATH)/lib/libnexaudiorenderer.so:system/lib/libnexaudiorenderer.so \
    $(LOCAL_PATH)/lib/libaudioeffectsole.so:system/lib/libaudioeffectsole.so \
    $(LOCAL_PATH)/lib/hw/camera.default.so:system/lib/hw/camera.mt6575.so \
    $(LOCAL_PATH)/lib/libcamera_client.so:system/lib/libcamera_client.so \
    $(LOCAL_PATH)/lib/libcameracustom.so:system/lib/libcameracustom.so \
    $(LOCAL_PATH)/lib/libcameraprofile.so:system/lib/libcameraprofile.so \
    $(LOCAL_PATH)/lib/libcamalgo.so:system/lib/libcamalgo.so \
    $(LOCAL_PATH)/lib/libmhal.so:system/lib/libmhal.so \
    $(LOCAL_PATH)/lib/libmhalmdp.so:system/lib/libmhalmdp.so \
    $(LOCAL_PATH)/lib/libmhalscenario.so:system/lib/libmhalscenario.so \
    $(LOCAL_PATH)/lib/libmhaldrv.so:system/lib/libmhaldrv.so \
    $(LOCAL_PATH)/lib/libmhalcontent.so:system/lib/libmhalcontent.so \
    $(LOCAL_PATH)/lib/libmhalpipe.so:system/lib/libmhalpipe.so \
    $(LOCAL_PATH)/lib/libmexif.so:system/lib/libmexif.so \
    $(LOCAL_PATH)/lib/libeis.so:system/lib/libeis.so \
    $(LOCAL_PATH)/lib/libmpoencoder.so:system/lib/libmpoencoder.so \
    $(LOCAL_PATH)/lib/libmpo.so:system/lib/libmpo.so \
    $(LOCAL_PATH)/lib/libutilitysw.so:system/lib/libutilitysw.so \
    $(LOCAL_PATH)/lib/libmatv_cust.so:system/lib/libmatv_cust.so \
    $(LOCAL_PATH)/lib/hw/gps.default.so:system/lib/hw/gps.default.so \
    $(LOCAL_PATH)/lib/hw/gralloc.default.so:system/lib/hw/gralloc.default.so \
    $(LOCAL_PATH)/lib/hw/hwcomposer.mt6575.so:system/lib/hw/hwcomposer.mt6575.so \
    $(LOCAL_PATH)/lib/hw/lights.default.so:system/lib/hw/lights.default.so \
    $(LOCAL_PATH)/lib/libproxyhal.so:system/lib/libproxyhal.so \
    $(LOCAL_PATH)/lib/hw/mmumapper.mt6575.so:system/lib/hw/mmumapper.mt6575.so \
    $(LOCAL_PATH)/lib/hw/power.default.so:system/lib/hw/power.default.so \
    $(LOCAL_PATH)/lib/hw/sensors.mt6575.so:system/lib/hw/sensors.mt6575.so \
    $(LOCAL_PATH)/lib/modules/ccci.ko:system/lib/modules/ccci.ko \
    $(LOCAL_PATH)/lib/modules/ccci_plat.ko:system/lib/modules/ccci_plat.ko \
    $(LOCAL_PATH)/lib/modules/ccmni.ko:system/lib/modules/ccmni.ko \
    $(LOCAL_PATH)/lib/modules/devinfo.ko:system/lib/modules/devinfo.ko \
    $(LOCAL_PATH)/lib/modules/m4u.ko:system/lib/modules/m4u.ko \
    $(LOCAL_PATH)/lib/modules/mtk_drvb.ko:system/lib/modules/mtk_drvb.ko \
    $(LOCAL_PATH)/lib/modules/mtk_hif_sdio.ko:system/lib/modules/mtk_hif_sdio.ko \
    $(LOCAL_PATH)/lib/modules/mtk_hif_sdio_mt6628.ko:system/lib/modules/mtk_hif_sdio_mt6628.ko \
    $(LOCAL_PATH)/lib/modules/mtklfb.ko:system/lib/modules/mtklfb.ko \
    $(LOCAL_PATH)/lib/modules/mtk_stp_bt.ko:system/lib/modules/mtk_stp_bt.ko \
    $(LOCAL_PATH)/lib/modules/mtk_stp_bt_mt6628.ko:system/lib/modules/mtk_stp_bt_mt6628.ko \
    $(LOCAL_PATH)/lib/modules/mtk_stp_gps.ko:system/lib/modules/mtk_stp_gps.ko \
    $(LOCAL_PATH)/lib/modules/mtk_stp_gps_mt6628.ko:system/lib/modules/mtk_stp_gps_mt6628.ko \
    $(LOCAL_PATH)/lib/modules/mtk_stp_uart.ko:system/lib/modules/mtk_stp_uart.ko \
    $(LOCAL_PATH)/lib/modules/mtk_stp_uart_mt6628.ko:system/lib/modules/mtk_stp_uart_mt6628.ko \
    $(LOCAL_PATH)/lib/modules/mtk_stp_wmt.ko:system/lib/modules/mtk_stp_wmt.ko \
    $(LOCAL_PATH)/lib/modules/mtk_stp_wmt_mt6628.ko:system/lib/modules/mtk_stp_wmt_mt6628.ko \
    $(LOCAL_PATH)/lib/modules/mtk_wmt_wifi.ko:system/lib/modules/mtk_wmt_wifi.ko \
    $(LOCAL_PATH)/lib/modules/mtk_wmt_wifi_mt6628.ko:system/lib/modules/mtk_wmt_wifi_mt6628.ko \
    $(LOCAL_PATH)/lib/modules/pvrsrvkm.ko:system/lib/modules/pvrsrvkm.ko \
    $(LOCAL_PATH)/lib/modules/sec.ko:system/lib/modules/sec.ko \
    $(LOCAL_PATH)/lib/modules/vcodec_kernel_driver.ko:system/lib/modules/vcodec_kernel_driver.ko \
    $(LOCAL_PATH)/lib/modules/wlan.ko:system/lib/modules/wlan.ko \
    $(LOCAL_PATH)/lib/modules/wlan_mt6620.ko:system/lib/modules/wlan_mt6620.ko \
    $(LOCAL_PATH)/vendor/bin/pvrsrvctl:system/vendor/bin/pvrsrvctl \
    $(LOCAL_PATH)/vendor/lib/egl/libEGL_mtk.so:system/vendor/lib/egl/libEGL_mtk.so \
    $(LOCAL_PATH)/vendor/lib/egl/libGLESv1_CM_mtk.so:system/vendor/lib/egl/libGLESv1_CM_mtk.so \
    $(LOCAL_PATH)/vendor/lib/egl/libGLESv2_mtk.so:system/vendor/lib/egl/libGLESv2_mtk.so \
    $(LOCAL_PATH)/vendor/lib/hw/gralloc.mt6575.so:system/vendor/lib/hw/gralloc.mt6575.so \
    $(LOCAL_PATH)/vendor/lib/libglslcompiler.so:system/vendor/lib/libglslcompiler.so \
    $(LOCAL_PATH)/vendor/lib/libIMGegl.so:system/vendor/lib/libIMGegl.so \
    $(LOCAL_PATH)/vendor/lib/libpvr2d.so:system/vendor/lib/libpvr2d.so \
    $(LOCAL_PATH)/vendor/lib/libpvrANDROID_WSEGL.so:system/vendor/lib/libpvrANDROID_WSEGL.so \
    $(LOCAL_PATH)/vendor/lib/libPVRScopeServices.so:system/vendor/lib/libPVRScopeServices.so \
    $(LOCAL_PATH)/vendor/lib/libsrv_init.so:system/vendor/lib/libsrv_init.so \
    $(LOCAL_PATH)/vendor/lib/libsrv_um.so:system/vendor/lib/libsrv_um.so \
    $(LOCAL_PATH)/vendor/lib/libusc.so:system/vendor/lib/libusc.so \
    $(LOCAL_PATH)/bin/ccci_mdinit:system/bin/ccci_mdinit \
    $(LOCAL_PATH)/bin/ccci_fsd:system/bin/ccci_fsd \
    $(LOCAL_PATH)/bin/ccci_rpcd:system/bin/ccci_rpcd \
    $(LOCAL_PATH)/bin/gsm0710muxd:system/bin/gsm0710muxd \
    $(LOCAL_PATH)/etc/firmware/modem.img:system/etc/firmware/modem.img \
    $(LOCAL_PATH)/etc/firmware/DSP_ROM:system/etc/firmware/DSP_ROM \
    $(LOCAL_PATH)/lib/liblgpart.so:system/lib/liblgpart.so \
    $(LOCAL_PATH)/lib/libnvram.so:system/lib/libnvram.so \
    $(LOCAL_PATH)/lib/libcustom_nvram.so:system/lib/libcustom_nvram.so \
    $(LOCAL_PATH)/lib/libnvram_daemon_callback.so:system/lib/libnvram_daemon_callback.so \
    $(LOCAL_PATH)/lib/libfile_op.so:system/lib/libfile_op.so \
    $(LOCAL_PATH)/lib/libhwm.so:system/lib/libhwm.so \
    $(LOCAL_PATH)/bin/nvram_daemon:system/bin/nvram_daemon \
    $(LOCAL_PATH)/bin/nvram_agent_binder:system/bin/nvram_agent_binder
